### ISSUE TITLE
Thread exception when doing install

### ISSUE THREAD

**Issue by shadowx787** [zeek/package-manager#62] opened 2020-03-24 21:13 UTC
Running zkg 2.0.7, and bro 2.6.1

I'm not sure if the issue is something I did wrong on my end or if it's an issue with package-manager.

When trying to install a bro/zeek package I get the following error:

> Exception in thread Thread-1:

> Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/bin/zkg", line 340, in run
    self.package_name, self.package_version)
  File "/usr/lib/python2.7/site-packages/zeekpkg/manager.py", line 2179, in install
    return self._install(matches[0], version)
  File "/usr/lib/python2.7/site-packages/zeekpkg/manager.py", line 2241, in _install
    status.current_hash = clone.head.object.hexsha
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 190, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 132, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 181, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 145, in _get_ref_info_helper
    with open(osp.join(repodir, ref_path), 'rt', encoding='UTF-8') as fp:
TypeError: 'encoding' is an invalid keyword argument for this function

> Traceback (most recent call last):
  File "/bin/zkg", line 2226, in <module>
    main()
  File "/bin/zkg", line 2222, in main
    args.run_cmd(manager, args, config, configfile)
  File "/bin/zkg", line 584, in cmd_install
    print('Installed "{}" ({})'.format(name, ipkg.status.current_version))
AttributeError: 'NoneType' object has no attribute 'status'

It appears the packages are downloaded on the system in both the clones directory and the scratch directory but they aren't actually being installed or put in the script directory.

**Comment by jsiwek** [comment] 2020-03-24 22:42
It may be caused by your version of GitPython.  Seems they maybe removed Python2 support recently (since it has reached end-of-life): https://gitpython.readthedocs.io/en/stable/changes.html#remove-python-2-support

The plan for `zkg`, too, is to soon explicitly remove Python2 support, so I'd suggest trying to update your environment to Python3 ASAP.  I'll go ahead and close this, but please let me know if you find things not working under Python3.

**Closed by jsiwek** 2020-03-24 22:42 UTC
